#pragma once

#include <string>
#include <unordered_map>
#include <vector>

namespace evnet::csv {

/// A parsed CSV row, addressable by header name.
class Row {
public:
    Row(const std::vector<std::string>* header, std::vector<std::string> fields, std::size_t lineNumber)
        : header_(header), fields_(std::move(fields)), lineNumber_(lineNumber) {}

    /// Throws std::runtime_error naming the column and line if absent or unparseable.
    const std::string& str(const std::string& column) const;
    double number(const std::string& column) const;
    int integer(const std::string& column) const;
    bool boolean(const std::string& column) const;

    bool has(const std::string& column) const;
    std::size_t lineNumber() const { return lineNumber_; }

private:
    std::size_t indexOf(const std::string& column) const;

    const std::vector<std::string>* header_;
    std::vector<std::string> fields_;
    std::size_t lineNumber_;
};

/// Minimal reader for the toolkit's own generated files.
///
/// Deliberately not a general CSV parser: it handles a `#` comment prefix, blank
/// lines, and surrounding whitespace, but not embedded commas or quoting. The
/// inputs are machine-generated by tools/build_datasets.py, so the useful
/// property here is that malformed input fails loudly with a line number --
/// which is precisely what the legacy loaders did not do. The corridor project's
/// `ss >> ch >> id >> ch >> ...` parse produced silent garbage on any
/// unexpected line, and the Sydney project's matrix reader was one value short
/// and never noticed.
class Reader {
public:
    /// Throws std::runtime_error if the file cannot be opened or has no header.
    explicit Reader(const std::string& path);

    const std::vector<std::string>& header() const { return header_; }
    const std::vector<Row>& rows() const { return rows_; }

    /// Throws unless every named column is present.
    void requireColumns(const std::vector<std::string>& columns) const;

private:
    std::string path_;
    std::vector<std::string> header_;
    std::vector<Row> rows_;
};

/// Escapes a field for output: quotes it when it contains a comma or a quote.
std::string escape(const std::string& field);

}  // namespace evnet::csv
